#include "dshot.h"
#include "stm32f401xc.h"
#include <stdbool.h>
#include <stddef.h>

/* DShot600 over TIM3 CH1-4 (PB0/1/4/5, same pins the analog PWM driver
   used). Each bit period is generated by loading TIM3's CCR1-4 with a
   new duty value once per timer Update event, using TIM3's DMA burst
   feature: TIM3_UP -> DMA1 Stream2 Channel5 (confirmed conflict-free -
   nothing else in this project uses DMA1 Stream2). One Update event
   re-triggers DBL+1 = 4 back-to-back DMA word-writes into TIM3->DMAR,
   which the timer internally routes to CCR1, CCR2, CCR3, CCR4 in turn
   (DCR.DBA points at CCR1, DCR.DBL = 3 for a 4-register burst). */

#define TIM3_CLK_HZ         84000000U
#define DSHOT_BIT_HZ        600000U /* DShot600 */
#define DSHOT_BIT_TICKS     (TIM3_CLK_HZ / DSHOT_BIT_HZ) /* 140 ticks/bit */

/* DShot bit encoding: "1" = ~75% high time, "0" = ~37.5% high time. */
#define DSHOT_T1H_TICKS     ((DSHOT_BIT_TICKS * 3U) / 4U)
#define DSHOT_T0H_TICKS     ((DSHOT_BIT_TICKS * 3U) / 8U)

#define DSHOT_FRAME_BITS    16U
#define DSHOT_FRAME_GAP     2U /* trailing zero-duty slots so the line settles low */
#define DSHOT_BURST_ROWS    (DSHOT_FRAME_BITS + DSHOT_FRAME_GAP)

/* CCR1 is the 14th 32-bit register in TIM_TypeDef (offset 0x34 / 4). */
#define TIM_DCR_CCR1_BASE   13U
#define TIM_DCR_BURST_4REGS 3U

/* TIM3_UP request -> DMA1 Stream2, Channel 5 (0b101 = CHSEL_2 | CHSEL_0). */
#define DSHOT_DMA_CHSEL     (DMA_SxCR_CHSEL_2 | DMA_SxCR_CHSEL_0)

static uint16_t dshot_throttle[NUM_DSHOT_CHANNELS];
static uint32_t dshot_burst_buffer[DSHOT_BURST_ROWS][NUM_DSHOT_CHANNELS];

static uint16_t dshot_encode_frame(uint16_t value) {
    uint16_t packet = (uint16_t) (value << 1); /* telemetry request bit left at 0 */
    uint16_t csum = 0;
    uint16_t csum_data = packet;

    for (uint8_t i = 0; i < 3U; i++) {
        csum ^= csum_data;
        csum_data >>= 4;
    }

    csum &= 0xFU;

    return (uint16_t) ((packet << 4) | csum);
}

static void dshot_fill_burst_buffer(void) {
    uint16_t frame[NUM_DSHOT_CHANNELS];

    for (uint8_t ch = 0; ch < NUM_DSHOT_CHANNELS; ch++) {
        frame[ch] = dshot_encode_frame(dshot_throttle[ch]);
    }

    for (uint8_t bit = 0; bit < DSHOT_FRAME_BITS; bit++) {
        uint8_t shift = (uint8_t) (DSHOT_FRAME_BITS - 1U - bit);

        for (uint8_t ch = 0; ch < NUM_DSHOT_CHANNELS; ch++) {
            bool bit_set = ((frame[ch] >> shift) & 0x1U) != 0U;
            dshot_burst_buffer[bit][ch] = bit_set ? DSHOT_T1H_TICKS : DSHOT_T0H_TICKS;
        }
    }

    for (uint8_t row = DSHOT_FRAME_BITS; row < DSHOT_BURST_ROWS; row++) {
        for (uint8_t ch = 0; ch < NUM_DSHOT_CHANNELS; ch++) {
            dshot_burst_buffer[row][ch] = 0U;
        }
    }
}

static void dshot_gpio_init(void) {
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;

    GPIOB->MODER &= ~(GPIO_MODER_MODE0 | GPIO_MODER_MODE1 | GPIO_MODER_MODE4 | GPIO_MODER_MODE5);
    GPIOB->MODER |= (0x2U << GPIO_MODER_MODE0_Pos) | (0x2U << GPIO_MODER_MODE1_Pos)
        | (0x2U << GPIO_MODER_MODE4_Pos) | (0x2U << GPIO_MODER_MODE5_Pos);

    GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPD0 | GPIO_PUPDR_PUPD1 | GPIO_PUPDR_PUPD4 | GPIO_PUPDR_PUPD5);

    GPIOB->OSPEEDR |= (0x2U << GPIO_OSPEEDR_OSPEED0_Pos) | (0x2U << GPIO_OSPEEDR_OSPEED1_Pos)
        | (0x2U << GPIO_OSPEEDR_OSPEED4_Pos) | (0x2U << GPIO_OSPEEDR_OSPEED5_Pos);

    /* AF2 = TIM3 on PB0/1/4/5 */
    GPIOB->AFR[0] &= ~((15U << 0) | (15U << 4) | (15U << 16) | (15U << 20));
    GPIOB->AFR[0] |= GPIO_AFRL_AFRL0_1 | GPIO_AFRL_AFRL1_1 | GPIO_AFRL_AFRL4_1 | GPIO_AFRL_AFRL5_1;
}

static void dshot_timer_init(void) {
    RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;

    TIM3->PSC = 0;
    TIM3->ARR = DSHOT_BIT_TICKS - 1U;

    TIM3->CCMR1 |= (0x6U << TIM_CCMR1_OC1M_Pos) | TIM_CCMR1_OC1PE;
    TIM3->CCMR1 |= (0x6U << TIM_CCMR1_OC2M_Pos) | TIM_CCMR1_OC2PE;
    TIM3->CCMR2 |= (0x6U << TIM_CCMR2_OC3M_Pos) | TIM_CCMR2_OC3PE;
    TIM3->CCMR2 |= (0x6U << TIM_CCMR2_OC4M_Pos) | TIM_CCMR2_OC4PE;

    TIM3->CCER |= TIM_CCER_CC1E | TIM_CCER_CC2E | TIM_CCER_CC3E | TIM_CCER_CC4E;

    TIM3->CCR1 = 0;
    TIM3->CCR2 = 0;
    TIM3->CCR3 = 0;
    TIM3->CCR4 = 0;

    TIM3->DCR = (TIM_DCR_CCR1_BASE << TIM_DCR_DBA_Pos) | (TIM_DCR_BURST_4REGS << TIM_DCR_DBL_Pos);
    TIM3->DIER |= TIM_DIER_UDE;

    TIM3->EGR |= TIM_EGR_UG;
    TIM3->CR1 |= TIM_CR1_CEN;
}

static void dshot_dma_init(void) {
    RCC->AHB1ENR |= RCC_AHB1ENR_DMA1EN;

    DMA1_Stream2->CR = 0;
    DMA1_Stream2->FCR = 0;
    DMA1_Stream2->PAR = (uint32_t) &TIM3->DMAR;
}

void dshot_init(void) {
    for (uint8_t ch = 0; ch < NUM_DSHOT_CHANNELS; ch++) {
        dshot_throttle[ch] = 0;
    }

    dshot_gpio_init();
    dshot_timer_init();
    dshot_dma_init();
}

void dshot_set_throttle(dshot_channel_t channel, uint16_t throttle) {
    if (channel >= NUM_DSHOT_CHANNELS) {
        return;
    }

    if ((throttle != 0U) && (throttle < DSHOT_THROTTLE_MIN)) {
        throttle = DSHOT_THROTTLE_MIN;
    }

    if (throttle > DSHOT_THROTTLE_MAX) {
        throttle = DSHOT_THROTTLE_MAX;
    }

    dshot_throttle[channel] = throttle;
}

void dshot_send(void) {
    if (DMA1_Stream2->CR & DMA_SxCR_EN) {
        return; /* previous frame still transmitting */
    }

    dshot_fill_burst_buffer();

    DMA1->LIFCR = DMA_LIFCR_CTCIF2 | DMA_LIFCR_CHTIF2 | DMA_LIFCR_CTEIF2
        | DMA_LIFCR_CDMEIF2 | DMA_LIFCR_CFEIF2;

    DMA1_Stream2->M0AR = (uint32_t) dshot_burst_buffer;
    DMA1_Stream2->NDTR = DSHOT_BURST_ROWS * NUM_DSHOT_CHANNELS;

    DMA1_Stream2->CR = DSHOT_DMA_CHSEL
        | DMA_SxCR_PSIZE_1
        | DMA_SxCR_MSIZE_1
        | DMA_SxCR_MINC
        | DMA_SxCR_DIR_0
        | DMA_SxCR_EN;
}
